//! Portable SHA-256 (FIPS 180-4) core: no intrinsics, no assembly, no `cfg`, so
//! it is the fallback and the differential-test oracle on every device.
//!
//! Written against ZeroNet's actual use rather than a bulk-file profile: the
//! VMess KDF runs sixteen short digests per handshake, so per-call overhead
//! dominates. `digest` therefore compresses whole blocks straight out of the
//! caller's slice and pads in place -- a one-block input is never copied through
//! a `BlockBuffer` -- and the schedule is expanded in place so it stays in
//! registers.

const IV: [u32; 8] = [
    0x6a09_e667, 0xbb67_ae85, 0x3c6e_f372, 0xa54f_f53a,
    0x510e_527f, 0x9b05_688c, 0x1f83_d9ab, 0x5be0_cd19,
];

#[inline(always)]
fn compress(state: &mut [u32; 8], blk: &[u8; 64]) {
    let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut h] = *state;
    let mut w = [0u32; 64];
    w[0] = u32::from_be_bytes([blk[0], blk[1], blk[2], blk[3]]);
    w[1] = u32::from_be_bytes([blk[4], blk[5], blk[6], blk[7]]);
    w[2] = u32::from_be_bytes([blk[8], blk[9], blk[10], blk[11]]);
    w[3] = u32::from_be_bytes([blk[12], blk[13], blk[14], blk[15]]);
    w[4] = u32::from_be_bytes([blk[16], blk[17], blk[18], blk[19]]);
    w[5] = u32::from_be_bytes([blk[20], blk[21], blk[22], blk[23]]);
    w[6] = u32::from_be_bytes([blk[24], blk[25], blk[26], blk[27]]);
    w[7] = u32::from_be_bytes([blk[28], blk[29], blk[30], blk[31]]);
    w[8] = u32::from_be_bytes([blk[32], blk[33], blk[34], blk[35]]);
    w[9] = u32::from_be_bytes([blk[36], blk[37], blk[38], blk[39]]);
    w[10] = u32::from_be_bytes([blk[40], blk[41], blk[42], blk[43]]);
    w[11] = u32::from_be_bytes([blk[44], blk[45], blk[46], blk[47]]);
    w[12] = u32::from_be_bytes([blk[48], blk[49], blk[50], blk[51]]);
    w[13] = u32::from_be_bytes([blk[52], blk[53], blk[54], blk[55]]);
    w[14] = u32::from_be_bytes([blk[56], blk[57], blk[58], blk[59]]);
    w[15] = u32::from_be_bytes([blk[60], blk[61], blk[62], blk[63]]);
    let (mut s0, mut s1, mut ch, mut maj, mut t1, mut t2) = (0u32, 0u32, 0u32, 0u32, 0u32, 0u32);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x428a2f98u32).wrapping_add(w[0]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x71374491u32).wrapping_add(w[1]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xb5c0fbcfu32).wrapping_add(w[2]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xe9b5dba5u32).wrapping_add(w[3]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x3956c25bu32).wrapping_add(w[4]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x59f111f1u32).wrapping_add(w[5]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x923f82a4u32).wrapping_add(w[6]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xab1c5ed5u32).wrapping_add(w[7]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xd807aa98u32).wrapping_add(w[8]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x12835b01u32).wrapping_add(w[9]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x243185beu32).wrapping_add(w[10]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x550c7dc3u32).wrapping_add(w[11]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x72be5d74u32).wrapping_add(w[12]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x80deb1feu32).wrapping_add(w[13]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x9bdc06a7u32).wrapping_add(w[14]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xc19bf174u32).wrapping_add(w[15]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[1].rotate_right(7) ^ w[1].rotate_right(18) ^ (w[1] >> 3);
    let p1 = w[14].rotate_right(17) ^ w[14].rotate_right(19) ^ (w[14] >> 10);
    w[16] = w[0].wrapping_add(p0).wrapping_add(w[9]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xe49b69c1u32).wrapping_add(w[16]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[2].rotate_right(7) ^ w[2].rotate_right(18) ^ (w[2] >> 3);
    let p1 = w[15].rotate_right(17) ^ w[15].rotate_right(19) ^ (w[15] >> 10);
    w[17] = w[1].wrapping_add(p0).wrapping_add(w[10]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xefbe4786u32).wrapping_add(w[17]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[3].rotate_right(7) ^ w[3].rotate_right(18) ^ (w[3] >> 3);
    let p1 = w[16].rotate_right(17) ^ w[16].rotate_right(19) ^ (w[16] >> 10);
    w[18] = w[2].wrapping_add(p0).wrapping_add(w[11]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x0fc19dc6u32).wrapping_add(w[18]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[4].rotate_right(7) ^ w[4].rotate_right(18) ^ (w[4] >> 3);
    let p1 = w[17].rotate_right(17) ^ w[17].rotate_right(19) ^ (w[17] >> 10);
    w[19] = w[3].wrapping_add(p0).wrapping_add(w[12]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x240ca1ccu32).wrapping_add(w[19]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[5].rotate_right(7) ^ w[5].rotate_right(18) ^ (w[5] >> 3);
    let p1 = w[18].rotate_right(17) ^ w[18].rotate_right(19) ^ (w[18] >> 10);
    w[20] = w[4].wrapping_add(p0).wrapping_add(w[13]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x2de92c6fu32).wrapping_add(w[20]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[6].rotate_right(7) ^ w[6].rotate_right(18) ^ (w[6] >> 3);
    let p1 = w[19].rotate_right(17) ^ w[19].rotate_right(19) ^ (w[19] >> 10);
    w[21] = w[5].wrapping_add(p0).wrapping_add(w[14]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x4a7484aau32).wrapping_add(w[21]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[7].rotate_right(7) ^ w[7].rotate_right(18) ^ (w[7] >> 3);
    let p1 = w[20].rotate_right(17) ^ w[20].rotate_right(19) ^ (w[20] >> 10);
    w[22] = w[6].wrapping_add(p0).wrapping_add(w[15]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x5cb0a9dcu32).wrapping_add(w[22]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[8].rotate_right(7) ^ w[8].rotate_right(18) ^ (w[8] >> 3);
    let p1 = w[21].rotate_right(17) ^ w[21].rotate_right(19) ^ (w[21] >> 10);
    w[23] = w[7].wrapping_add(p0).wrapping_add(w[16]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x76f988dau32).wrapping_add(w[23]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[9].rotate_right(7) ^ w[9].rotate_right(18) ^ (w[9] >> 3);
    let p1 = w[22].rotate_right(17) ^ w[22].rotate_right(19) ^ (w[22] >> 10);
    w[24] = w[8].wrapping_add(p0).wrapping_add(w[17]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x983e5152u32).wrapping_add(w[24]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[10].rotate_right(7) ^ w[10].rotate_right(18) ^ (w[10] >> 3);
    let p1 = w[23].rotate_right(17) ^ w[23].rotate_right(19) ^ (w[23] >> 10);
    w[25] = w[9].wrapping_add(p0).wrapping_add(w[18]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xa831c66du32).wrapping_add(w[25]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[11].rotate_right(7) ^ w[11].rotate_right(18) ^ (w[11] >> 3);
    let p1 = w[24].rotate_right(17) ^ w[24].rotate_right(19) ^ (w[24] >> 10);
    w[26] = w[10].wrapping_add(p0).wrapping_add(w[19]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xb00327c8u32).wrapping_add(w[26]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[12].rotate_right(7) ^ w[12].rotate_right(18) ^ (w[12] >> 3);
    let p1 = w[25].rotate_right(17) ^ w[25].rotate_right(19) ^ (w[25] >> 10);
    w[27] = w[11].wrapping_add(p0).wrapping_add(w[20]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xbf597fc7u32).wrapping_add(w[27]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[13].rotate_right(7) ^ w[13].rotate_right(18) ^ (w[13] >> 3);
    let p1 = w[26].rotate_right(17) ^ w[26].rotate_right(19) ^ (w[26] >> 10);
    w[28] = w[12].wrapping_add(p0).wrapping_add(w[21]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xc6e00bf3u32).wrapping_add(w[28]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[14].rotate_right(7) ^ w[14].rotate_right(18) ^ (w[14] >> 3);
    let p1 = w[27].rotate_right(17) ^ w[27].rotate_right(19) ^ (w[27] >> 10);
    w[29] = w[13].wrapping_add(p0).wrapping_add(w[22]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xd5a79147u32).wrapping_add(w[29]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[15].rotate_right(7) ^ w[15].rotate_right(18) ^ (w[15] >> 3);
    let p1 = w[28].rotate_right(17) ^ w[28].rotate_right(19) ^ (w[28] >> 10);
    w[30] = w[14].wrapping_add(p0).wrapping_add(w[23]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x06ca6351u32).wrapping_add(w[30]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[16].rotate_right(7) ^ w[16].rotate_right(18) ^ (w[16] >> 3);
    let p1 = w[29].rotate_right(17) ^ w[29].rotate_right(19) ^ (w[29] >> 10);
    w[31] = w[15].wrapping_add(p0).wrapping_add(w[24]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x14292967u32).wrapping_add(w[31]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[17].rotate_right(7) ^ w[17].rotate_right(18) ^ (w[17] >> 3);
    let p1 = w[30].rotate_right(17) ^ w[30].rotate_right(19) ^ (w[30] >> 10);
    w[32] = w[16].wrapping_add(p0).wrapping_add(w[25]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x27b70a85u32).wrapping_add(w[32]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[18].rotate_right(7) ^ w[18].rotate_right(18) ^ (w[18] >> 3);
    let p1 = w[31].rotate_right(17) ^ w[31].rotate_right(19) ^ (w[31] >> 10);
    w[33] = w[17].wrapping_add(p0).wrapping_add(w[26]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x2e1b2138u32).wrapping_add(w[33]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[19].rotate_right(7) ^ w[19].rotate_right(18) ^ (w[19] >> 3);
    let p1 = w[32].rotate_right(17) ^ w[32].rotate_right(19) ^ (w[32] >> 10);
    w[34] = w[18].wrapping_add(p0).wrapping_add(w[27]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x4d2c6dfcu32).wrapping_add(w[34]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[20].rotate_right(7) ^ w[20].rotate_right(18) ^ (w[20] >> 3);
    let p1 = w[33].rotate_right(17) ^ w[33].rotate_right(19) ^ (w[33] >> 10);
    w[35] = w[19].wrapping_add(p0).wrapping_add(w[28]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x53380d13u32).wrapping_add(w[35]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[21].rotate_right(7) ^ w[21].rotate_right(18) ^ (w[21] >> 3);
    let p1 = w[34].rotate_right(17) ^ w[34].rotate_right(19) ^ (w[34] >> 10);
    w[36] = w[20].wrapping_add(p0).wrapping_add(w[29]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x650a7354u32).wrapping_add(w[36]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[22].rotate_right(7) ^ w[22].rotate_right(18) ^ (w[22] >> 3);
    let p1 = w[35].rotate_right(17) ^ w[35].rotate_right(19) ^ (w[35] >> 10);
    w[37] = w[21].wrapping_add(p0).wrapping_add(w[30]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x766a0abbu32).wrapping_add(w[37]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[23].rotate_right(7) ^ w[23].rotate_right(18) ^ (w[23] >> 3);
    let p1 = w[36].rotate_right(17) ^ w[36].rotate_right(19) ^ (w[36] >> 10);
    w[38] = w[22].wrapping_add(p0).wrapping_add(w[31]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x81c2c92eu32).wrapping_add(w[38]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[24].rotate_right(7) ^ w[24].rotate_right(18) ^ (w[24] >> 3);
    let p1 = w[37].rotate_right(17) ^ w[37].rotate_right(19) ^ (w[37] >> 10);
    w[39] = w[23].wrapping_add(p0).wrapping_add(w[32]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x92722c85u32).wrapping_add(w[39]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[25].rotate_right(7) ^ w[25].rotate_right(18) ^ (w[25] >> 3);
    let p1 = w[38].rotate_right(17) ^ w[38].rotate_right(19) ^ (w[38] >> 10);
    w[40] = w[24].wrapping_add(p0).wrapping_add(w[33]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xa2bfe8a1u32).wrapping_add(w[40]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[26].rotate_right(7) ^ w[26].rotate_right(18) ^ (w[26] >> 3);
    let p1 = w[39].rotate_right(17) ^ w[39].rotate_right(19) ^ (w[39] >> 10);
    w[41] = w[25].wrapping_add(p0).wrapping_add(w[34]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xa81a664bu32).wrapping_add(w[41]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[27].rotate_right(7) ^ w[27].rotate_right(18) ^ (w[27] >> 3);
    let p1 = w[40].rotate_right(17) ^ w[40].rotate_right(19) ^ (w[40] >> 10);
    w[42] = w[26].wrapping_add(p0).wrapping_add(w[35]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xc24b8b70u32).wrapping_add(w[42]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[28].rotate_right(7) ^ w[28].rotate_right(18) ^ (w[28] >> 3);
    let p1 = w[41].rotate_right(17) ^ w[41].rotate_right(19) ^ (w[41] >> 10);
    w[43] = w[27].wrapping_add(p0).wrapping_add(w[36]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xc76c51a3u32).wrapping_add(w[43]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[29].rotate_right(7) ^ w[29].rotate_right(18) ^ (w[29] >> 3);
    let p1 = w[42].rotate_right(17) ^ w[42].rotate_right(19) ^ (w[42] >> 10);
    w[44] = w[28].wrapping_add(p0).wrapping_add(w[37]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xd192e819u32).wrapping_add(w[44]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[30].rotate_right(7) ^ w[30].rotate_right(18) ^ (w[30] >> 3);
    let p1 = w[43].rotate_right(17) ^ w[43].rotate_right(19) ^ (w[43] >> 10);
    w[45] = w[29].wrapping_add(p0).wrapping_add(w[38]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xd6990624u32).wrapping_add(w[45]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[31].rotate_right(7) ^ w[31].rotate_right(18) ^ (w[31] >> 3);
    let p1 = w[44].rotate_right(17) ^ w[44].rotate_right(19) ^ (w[44] >> 10);
    w[46] = w[30].wrapping_add(p0).wrapping_add(w[39]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xf40e3585u32).wrapping_add(w[46]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[32].rotate_right(7) ^ w[32].rotate_right(18) ^ (w[32] >> 3);
    let p1 = w[45].rotate_right(17) ^ w[45].rotate_right(19) ^ (w[45] >> 10);
    w[47] = w[31].wrapping_add(p0).wrapping_add(w[40]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x106aa070u32).wrapping_add(w[47]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[33].rotate_right(7) ^ w[33].rotate_right(18) ^ (w[33] >> 3);
    let p1 = w[46].rotate_right(17) ^ w[46].rotate_right(19) ^ (w[46] >> 10);
    w[48] = w[32].wrapping_add(p0).wrapping_add(w[41]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x19a4c116u32).wrapping_add(w[48]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[34].rotate_right(7) ^ w[34].rotate_right(18) ^ (w[34] >> 3);
    let p1 = w[47].rotate_right(17) ^ w[47].rotate_right(19) ^ (w[47] >> 10);
    w[49] = w[33].wrapping_add(p0).wrapping_add(w[42]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x1e376c08u32).wrapping_add(w[49]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[35].rotate_right(7) ^ w[35].rotate_right(18) ^ (w[35] >> 3);
    let p1 = w[48].rotate_right(17) ^ w[48].rotate_right(19) ^ (w[48] >> 10);
    w[50] = w[34].wrapping_add(p0).wrapping_add(w[43]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x2748774cu32).wrapping_add(w[50]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[36].rotate_right(7) ^ w[36].rotate_right(18) ^ (w[36] >> 3);
    let p1 = w[49].rotate_right(17) ^ w[49].rotate_right(19) ^ (w[49] >> 10);
    w[51] = w[35].wrapping_add(p0).wrapping_add(w[44]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x34b0bcb5u32).wrapping_add(w[51]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[37].rotate_right(7) ^ w[37].rotate_right(18) ^ (w[37] >> 3);
    let p1 = w[50].rotate_right(17) ^ w[50].rotate_right(19) ^ (w[50] >> 10);
    w[52] = w[36].wrapping_add(p0).wrapping_add(w[45]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x391c0cb3u32).wrapping_add(w[52]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[38].rotate_right(7) ^ w[38].rotate_right(18) ^ (w[38] >> 3);
    let p1 = w[51].rotate_right(17) ^ w[51].rotate_right(19) ^ (w[51] >> 10);
    w[53] = w[37].wrapping_add(p0).wrapping_add(w[46]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x4ed8aa4au32).wrapping_add(w[53]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[39].rotate_right(7) ^ w[39].rotate_right(18) ^ (w[39] >> 3);
    let p1 = w[52].rotate_right(17) ^ w[52].rotate_right(19) ^ (w[52] >> 10);
    w[54] = w[38].wrapping_add(p0).wrapping_add(w[47]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x5b9cca4fu32).wrapping_add(w[54]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[40].rotate_right(7) ^ w[40].rotate_right(18) ^ (w[40] >> 3);
    let p1 = w[53].rotate_right(17) ^ w[53].rotate_right(19) ^ (w[53] >> 10);
    w[55] = w[39].wrapping_add(p0).wrapping_add(w[48]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x682e6ff3u32).wrapping_add(w[55]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[41].rotate_right(7) ^ w[41].rotate_right(18) ^ (w[41] >> 3);
    let p1 = w[54].rotate_right(17) ^ w[54].rotate_right(19) ^ (w[54] >> 10);
    w[56] = w[40].wrapping_add(p0).wrapping_add(w[49]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x748f82eeu32).wrapping_add(w[56]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[42].rotate_right(7) ^ w[42].rotate_right(18) ^ (w[42] >> 3);
    let p1 = w[55].rotate_right(17) ^ w[55].rotate_right(19) ^ (w[55] >> 10);
    w[57] = w[41].wrapping_add(p0).wrapping_add(w[50]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x78a5636fu32).wrapping_add(w[57]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[43].rotate_right(7) ^ w[43].rotate_right(18) ^ (w[43] >> 3);
    let p1 = w[56].rotate_right(17) ^ w[56].rotate_right(19) ^ (w[56] >> 10);
    w[58] = w[42].wrapping_add(p0).wrapping_add(w[51]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x84c87814u32).wrapping_add(w[58]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[44].rotate_right(7) ^ w[44].rotate_right(18) ^ (w[44] >> 3);
    let p1 = w[57].rotate_right(17) ^ w[57].rotate_right(19) ^ (w[57] >> 10);
    w[59] = w[43].wrapping_add(p0).wrapping_add(w[52]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x8cc70208u32).wrapping_add(w[59]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[45].rotate_right(7) ^ w[45].rotate_right(18) ^ (w[45] >> 3);
    let p1 = w[58].rotate_right(17) ^ w[58].rotate_right(19) ^ (w[58] >> 10);
    w[60] = w[44].wrapping_add(p0).wrapping_add(w[53]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0x90befffau32).wrapping_add(w[60]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[46].rotate_right(7) ^ w[46].rotate_right(18) ^ (w[46] >> 3);
    let p1 = w[59].rotate_right(17) ^ w[59].rotate_right(19) ^ (w[59] >> 10);
    w[61] = w[45].wrapping_add(p0).wrapping_add(w[54]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xa4506cebu32).wrapping_add(w[61]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[47].rotate_right(7) ^ w[47].rotate_right(18) ^ (w[47] >> 3);
    let p1 = w[60].rotate_right(17) ^ w[60].rotate_right(19) ^ (w[60] >> 10);
    w[62] = w[46].wrapping_add(p0).wrapping_add(w[55]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xbef9a3f7u32).wrapping_add(w[62]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    let p0 = w[48].rotate_right(7) ^ w[48].rotate_right(18) ^ (w[48] >> 3);
    let p1 = w[61].rotate_right(17) ^ w[61].rotate_right(19) ^ (w[61] >> 10);
    w[63] = w[47].wrapping_add(p0).wrapping_add(w[56]).wrapping_add(p1);
    s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
    ch = (e & f) ^ ((!e) & g);
    t1 = h.wrapping_add(s1).wrapping_add(ch).wrapping_add(0xc67178f2u32).wrapping_add(w[63]);
    s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
    maj = (a & b) ^ (a & c) ^ (b & c);
    t2 = s0.wrapping_add(maj);
    h = g; g = f; f = e; e = d.wrapping_add(t1);
    d = c; c = b; b = a; a = t1.wrapping_add(t2);
    state[0] = state[0].wrapping_add(a);
    state[1] = state[1].wrapping_add(b);
    state[2] = state[2].wrapping_add(c);
    state[3] = state[3].wrapping_add(d);
    state[4] = state[4].wrapping_add(e);
    state[5] = state[5].wrapping_add(f);
    state[6] = state[6].wrapping_add(g);
    state[7] = state[7].wrapping_add(h);
}

#[inline(always)]
fn compress_run(state: &mut [u32; 8], mut data: &[u8]) {
    while data.len() >= 64 {
        compress(state, data[..64].try_into().unwrap());
        data = &data[64..];
    }
}

/// One-shot SHA-256. Never copies the message.
pub fn digest(msg: &[u8]) -> [u8; 32] {
    let mut state = IV;
    let bitlen = (msg.len() as u64).wrapping_mul(8);
    let whole = msg.len() & !63;
    compress_run(&mut state, &msg[..whole]);

    let rest = &msg[whole..];
    let mut last = [0u8; 128];
    last[..rest.len()].copy_from_slice(rest);
    last[rest.len()] = 0x80;
    let end = if rest.len() + 1 + 8 <= 64 { 64 } else { 128 };
    last[end - 8..end].copy_from_slice(&bitlen.to_be_bytes());
    compress_run(&mut state, &last[..end]);

    let mut out = [0u8; 32];
    for (i, w) in state.iter().enumerate() {
        out[i * 4..i * 4 + 4].copy_from_slice(&w.to_be_bytes());
    }
    out
}
